name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        foo:
          - a
          - b
          - c
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo ${{ matrix.foo }}
